spring:
  profiles:
    active: dev,native #使用本地目录读取配置文件，而不是从版本仓库
  application:
    name: sc-config
  cloud:
    config:
      server:
        native:
          searchLocations: file:/Users/zhujie/Documents/devel/Java/sc-cloud/support/config #需要从sc-cloud目录下运行程序
          #searchLocations:classpath:/config
        #git:
        #  uri: http://xxx.git
        #  searchPaths: config #配置文件放在根目录时不需要配置
server:
  port: 9002

#取消权限验证
management:
  security:
    enabled: false

# 启用/restart端点重新启动应用程序上下文。
endpoints:
  restart:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

---
# dev profile
spring:
  profiles: dev

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

---
# docker profile
spring:
  profiles: docker

  rabbitmq:
      host: rabbitmq
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
     defaultZone: http://sc-registry-0.sc-registry.default.svc.cluster.local:9001/eureka/,http://sc-registry-1.sc-registry.default.svc.cluster.local:9001/eureka/

