spring:
  application:
    name: sc-zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin
server:
  port: 9003
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/