apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 32002
    - port: 9200
      targetPort: 9200
    - port: 5044
      targetPort: 5044
    - port: 4560
      targetPort: 4560
  selector:
    name: elk

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
spec:
  selector:
    matchLabels:
      app: elk
  replicas: 1
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
      - name: elk
        image: jamsa/elk
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 5044
        - containerPort: 4560
