eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: sc-gateway
server:
  port: 9000
zuul:
  routes:
    sc-consumer:
      path: /api/**
      serviceId: sc-consumer
management:
  security:
    enabled: false

