spring:
  profiles:
    active: dev
  application:
    name: sc-registry
server:
  port: 9001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#取消权限验证
management:
  security:
    enabled: false


# 启用/restart端点重新启动应用程序上下文。
endpoints:
  restart:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

---
# dev profile
spring:
  profiles: dev

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
# docker profile
spring:
  profiles: docker

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}-0.eureka.default.svc.cluster.local:${server.port}/eureka/,http://${eureka.instance.hostname}-1.eureka.default.svc.cluster.local:${server.port}/eureka/
