#公共配置

spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    bus:
      trace:
        enabled: true

#取消权限验证
management:
  security:
    enabled: false


# 启用/restart端点重新启动应用程序上下文。
endpoints:
  restart:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

---
# dev profile
spring:
  profiles: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
# docker profile
spring:
  profiles: docker

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
